name: '42valgrind Leak checker'
author: 'solareenlo'
description: 'Run valgrind on ubuntu-latest'
branding:
  icon: 'play-circle'
  color: 'green'

inputs:
  flags:
    description: 'Flags passed to valgrind'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://solareenlo/42valgrind:latest'
  entrypoint: /bin/bash
  flags:
    - -c
    - valgrind --leak-check=full --show-leak-kinds=all ${{ inputs.flags }}
